#!/bin/bash
if command -v star-logs &> /dev/null; then
	exec star-logs "$@"
fi

if command -v curl &> /dev/null; then
	set -o pipefail
	curl -fsSL https://raw.githubusercontent.com/StarLabsLtd/logs/main/star-logs | bash
	exit $?
fi

printf "star-logs-arch is deprecated. Please run star-logs instead.\n"
exit 1
